name: Publish bayesmix-env image

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push bayesmix-env Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MARIO_DOCKERHUB_USERNAME }}
          password: ${{ secrets.MARIO_DOCKERHUB_PASSWORD }}
      
      - name: Build and push bayesmix-env
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: resources/docker/env/Dockerfile
          tags: mberaha/bayesmix-env:latest
